name: Tests pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [16.x]
        medusajs-version: [1.2.1, 1.3.0]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-verion }}

      - name: 'npm install'
        run: npm install

      - name: 'run unit tests'
        run: npm run test:ci
        env:
          MEDUSAJS_VERSION: ${{ matrix.medusajs-version }}

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-verion: [16.x]
        medusajs-version: [1.2.1, 1.3.0]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: medusa-extender
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-verion }}

      - name: 'run integration tests'
        run: npm run test:integration:ci
        env:
          MEDUSAJS_VERSION: ${{ matrix.medusajs-version }}
          DB_PASSWORD: postgres
          IS_CI: true